#!/bin/sh

# https://github.com/psf/black
# https://hub.docker.com/r/pyfound/black

# docker pull pyfond/black:21.9b0

/usr/bin/docker run \
    -it \
    --rm \
    --entrypoint black \
    --user "$(id -u)":"$(id -g)" \
    -v "$PWD":/workdir \
    --workdir /workdir \
    pyfound/black:21.9b0 "$@"
