#!/bin/sh

# https://hub.docker.com/_/composer/

/usr/bin/docker run \
    -it \
    --rm \
    --net host \
    --user "$(id -u)":"$(id -g)" \
    --volume "$PWD:/workdir" \
    --workdir /workdir \
    composer:latest "$@"
