#!/usr/bin/env sh

# https://hub.docker.com/_/composer/

/usr/bin/docker run \
    --interactive \
    --net host \
    --rm \
    --tty \
    --user $(id -u):$(id -g) \
    --volume $PWD:/workdir \
    --workdir /workdir \
    composer:latest "$@"
