#!/usr/bin/env sh

# https://github.com/denisidoro/navi

# install
# docker pull karpoke/navi

# navi search nmap
# navi query systemctl
# navi widget bash
docker run \
    -it \
    --rm \
    karpoke/navi "$@"
