#!/bin/sh

# https://hub.docker.com/_/node/

# docker pull node:17.0.1

/usr/bin/docker run \
    -it \
    --rm \
    --entrypoint node \
    --net host \
    --user "$(id -u)":"$(id -g)" \
    --volume "$PWD:/workdir" \
    --workdir /workdir \
    node:17.0.1 "$@"
