#!/bin/sh

# https://hub.docker.com/_/node/

# docker pull node:16.3.0  # latest lts

/usr/bin/docker run \
    -it \
    --rm \
    --entrypoint node \
    --net host \
    --user "$(id -u)":"$(id -g)" \
    --volume "$PWD:/workdir" \
    --workdir /workdir \
    node:16.3.0 "$@"
