#!/usr/bin/env sh

# https://hub.docker.com/_/node/

/usr/bin/docker run \
    -it \
    --rm \
    --entrypoint npm \
    --net host \
    --user "$(id -u)":"$(id -g)" \
    --volume "$PWD:/workdir" \
    --workdir /workdir \
    node:latest "$@"
